# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: creating artifacts folder
          command: mkdir /tmp/artifacts
      - run:
          name: "install clojure"
          command: curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh && chmod +x linux-install-1.10.1.466.sh && sudo ./linux-install-1.10.1.466.sh
      - run:
          name: "downloading graalvm"
          command: curl -L https://github.com/oracle/graal/releases/download/vm-19.1.1/graalvm-ce-linux-amd64-19.1.1.tar.gz | tar -xz
      - run:
          name: "set graalvm path"
          command: echo 'export GRAALVM_HOME=./graalvm-ce-19.1.1' >> $BASH_ENV
      - run:
          name: "install native-image using gu"
          command: $GRAALVM_HOME/bin/gu install native-image
      - run:
          name: "build"
          command: clojure -A:native-image
      - run:
          name: move artifact to folder
          command: mv ./wah2wat /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

